# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PacketTunnel' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PacketTunnel

end

target 'WormholeX-Objc' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WormholeX-Objc

end
